version: "3.9"

services:

  db:
    image: postgres:16-alpine
    container_name: bid_db
    restart: unless-stopped
    environment:
      POSTGRES_DB:       ${PG_DB}
      POSTGRES_USER:     ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  app:
    build: .
    container_name: bid_hospital
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8051:8051"
    volumes:
      - ./dados_ocupacao:/app/dados_ocupacao
      - ./dados_fluxo:/app/dados_fluxo
    depends_on:
      - db

volumes:
  pgdata:
